### ISSUE TITLE
Some suggestions…

### ISSUE THREAD

**Issue by raptazure** [liuziming2001/Some-typical-problems-and-solution-of-C-language#1]
Proposal: 
1. Upload c file directly so that you can get syntax highlight.
2. Try to add more instructions in English.
3. Learn to use git to make your work more efficient.
4. However, just a good start!

**Comment by liuziming2001** [comment]
> Proposal:
> 
> 1. Upload c file directly so that you can get syntax highlight.
> 2. Try to add more instructions in English.
> 3. Learn to use git to make your work more efficient.
> 4. However, just a good start!

Thank you for your valueable suggestions.It is a shame that I didn't know how to use "issues" and what are they for until now:laughing: @raptazure

**Comment by raptazure** [comment]
> > Proposal:
> > 
> > 1. Upload c file directly so that you can get syntax highlight.
> > 2. Try to add more instructions in English.
> > 3. Learn to use git to make your work more efficient.
> > 4. However, just a good start!
> 
> Thank you for your valueable suggestions.It is a shame that I didn't know how to use "issues" and what are they for until now😆 @raptazure

You are welcome 🦀️
